In [1]:
from __future__ import print_function, division

In [2]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import datetime

In [3]:
# read data and preview data

# Source: http://web.mta.info/developers/turnstile.html
def get_data(week_nums):
    # base url
    url = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_{}.txt"
    dfs = []
    for week_num in week_nums:
        # concat our week onto url.. 
        file_url = url.format(week_num)
        dfs.append(pd.read_csv(file_url))
    return pd.concat(dfs)
        
week_nums = [170506, 170513, 170520, 170527, 170603]
df = get_data(week_nums)

df.head()

C/A  UNIT       SCP STATION LINENAME DIVISION        DATE      TIME  \
0  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  00:00:00   
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  04:00:00   
2  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  08:00:00   
3  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  12:00:00   
4  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  16:00:00   

      DESC  ENTRIES  \
0  REGULAR  6157740   
1  REGULAR  6157777   
2  REGULAR  6157810   
3  REGULAR  6157963   
4  REGULAR  6158212   

   EXITS                                                                 
0                                            2085315                     
1                                            2085319                     
2                                            2085353                     
3                                            2085453                     
4                                            2085529

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 981047 entries, 0 to 195957
Data columns (total 11 columns):
C/A                                                                     981047 non-null object
UNIT                                                                    981047 non-null object
SCP                                                                     981047 non-null object
STATION                                                                 981047 non-null object
LINENAME                                                                981047 non-null object
DIVISION                                                                981047 non-null object
DATE                                                                    981047 non-null object
TIME                                                                    981047 non-null object
DESC                                                                    981047 non-null object
ENTRIES                           

In [5]:
#check to make sure dimensions match entries
df.shape

(981047, 11)

In [6]:
df.tail()

C/A  UNIT       SCP        STATION LINENAME DIVISION        DATE  \
195953  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
195954  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
195955  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
195956  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
195957  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   

            TIME     DESC  ENTRIES  \
195953  05:00:00  REGULAR     5554   
195954  09:00:00  REGULAR     5554   
195955  13:00:00  REGULAR     5554   
195956  17:00:00  REGULAR     5554   
195957  21:00:00  REGULAR     5554   

        EXITS                                                                 
195953                                                299                     
195954                                                299                     
195955                                                299                     
195956                                                299                     
195957                                                299

Because indices in df above do not match number of rows in the dataframe, data is inconsistent and reset of indices is necessary.

In [7]:
#check an index, here index =1 
df.loc[1]

C/A  UNIT       SCP STATION LINENAME DIVISION        DATE      TIME  \
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  04/29/2017  04:00:00   
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  05/06/2017  04:00:00   
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  05/13/2017  04:00:00   
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  05/20/2017  04:00:00   
1  A002  R051  02-00-00   59 ST  NQR456W      BMT  05/27/2017  04:00:00   

      DESC  ENTRIES  \
1  REGULAR  6157777   
1  REGULAR  6166420   
1  REGULAR  6176001   
1  REGULAR  6184865   
1  REGULAR  6195240   

   EXITS                                                                 
1                                            2085319                     
1                                            2088525                     
1                                            2091936                     
1                                            2095167                     
1                                            2098318

In [8]:
# drop duplicate indices

df=df.reset_index()
df=df.drop('index',1)
df.tail()

C/A  UNIT       SCP        STATION LINENAME DIVISION        DATE  \
981042  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
981043  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
981044  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
981045  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   
981046  TRAM2  R469  00-05-01  RIT-ROOSEVELT        R      RIT  06/02/2017   

            TIME     DESC  ENTRIES  \
981042  05:00:00  REGULAR     5554   
981043  09:00:00  REGULAR     5554   
981044  13:00:00  REGULAR     5554   
981045  17:00:00  REGULAR     5554   
981046  21:00:00  REGULAR     5554   

        EXITS                                                                 
981042                                                299                     
981043                                                299                     
981044                                                299                     
981045                                                299                     
981046                                                299

Df above shows indices are reindexed successfully.

In [9]:
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               '],
      dtype='object')

In [10]:
# strip whitespace on Exits column
df.columns = [column.strip() for column in df.columns]

In [11]:
#drop unnecessary columns
df = df.drop(['LINENAME','DIVISION'],axis=1)

In [12]:
#check unnecessary columns are dropped
df.head()

C/A  UNIT       SCP STATION        DATE      TIME     DESC  ENTRIES  \
0  A002  R051  02-00-00   59 ST  04/29/2017  00:00:00  REGULAR  6157740   
1  A002  R051  02-00-00   59 ST  04/29/2017  04:00:00  REGULAR  6157777   
2  A002  R051  02-00-00   59 ST  04/29/2017  08:00:00  REGULAR  6157810   
3  A002  R051  02-00-00   59 ST  04/29/2017  12:00:00  REGULAR  6157963   
4  A002  R051  02-00-00   59 ST  04/29/2017  16:00:00  REGULAR  6158212   

     EXITS  
0  2085315  
1  2085319  
2  2085353  
3  2085453  
4  2085529

Df above shows columns successfully dropped.

In [13]:
#create datetime column
df['DATETIME'] = [pd.to_datetime(i+j, format = '%m/%d/%Y%H:%M:%S') for i, j in zip(df.DATE, df.TIME)]

In [14]:
df.head()

C/A  UNIT       SCP STATION        DATE      TIME     DESC  ENTRIES  \
0  A002  R051  02-00-00   59 ST  04/29/2017  00:00:00  REGULAR  6157740   
1  A002  R051  02-00-00   59 ST  04/29/2017  04:00:00  REGULAR  6157777   
2  A002  R051  02-00-00   59 ST  04/29/2017  08:00:00  REGULAR  6157810   
3  A002  R051  02-00-00   59 ST  04/29/2017  12:00:00  REGULAR  6157963   
4  A002  R051  02-00-00   59 ST  04/29/2017  16:00:00  REGULAR  6158212   

     EXITS            DATETIME  
0  2085315 2017-04-29 00:00:00  
1  2085319 2017-04-29 04:00:00  
2  2085353 2017-04-29 08:00:00  
3  2085453 2017-04-29 12:00:00  
4  2085529 2017-04-29 16:00:00

In [15]:
#verify that "C/A", "UNIT", "SCP", "STATION", "DATE_TIME" is unique
(df
 .groupby(["C/A", "UNIT", "SCP", "STATION", "DATE", "DATETIME"])
 .ENTRIES.count()
 .reset_index()
 .sort_values("ENTRIES", ascending=False))

C/A  UNIT       SCP          STATION        DATE  \
871022   R504  R276  00-00-01   VERNON-JACKSON  05/26/2017   
135038   G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017   
0        A002  R051  02-00-00            59 ST  04/29/2017   
654035   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654024   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654025   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654026   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654027   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654028   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654029   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654030   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654031   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654032   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654033   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654034   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654036   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654050   R145  R032  00-00-03   TIMES SQ-42 ST  05/16/2017   
654037   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654038   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654039   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654040   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654041   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654042   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654043   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654044   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654045   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654046   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654047   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654048   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654023   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
...       ...   ...       ...              ...         ...   
327026   N181  R357  00-00-01  AQUEDUCT N.COND  05/03/2017   
327025   N181  R357  00-00-01  AQUEDUCT N.COND  05/03/2017   
327024   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327023   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
326998   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
326999   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
327000   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
327001   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327002   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327003   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327004   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327005   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327006   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327007   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327008   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327009   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327010   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327011   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327012   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327013   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327014   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327015   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327016   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327017   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327018   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327019   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327020   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327021   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327022   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
981044  TRAM2  R469  00-05-01    RIT-ROOSEVELT  06/02/2017   

                  DATETIME  ENTRIES  
871022 2017-05-26 20:00:00        2  
135038 2017-05-09 05:00:00        2  
0      2017-04-29 00:00:00        1  
654035 2017-0

From the df above, there are 2 duplicate entries in this dataset.

In [16]:
#check first entry of duplicate entries in df above
# On 2017-05-26 20:00:00
mask = ((df["C/A"] == "R504") & 
(df["UNIT"] == "R276") & 
(df["SCP"] == "00-00-01") & 
(df["STATION"] == "VERNON-JACKSON") &
(df["DATE"] == "05/26/2017"))
df[mask]

C/A  UNIT       SCP         STATION        DATE      TIME  \
763074  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  00:00:00   
763075  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  04:00:00   
763076  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  08:00:00   
763077  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  12:00:00   
763078  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  16:00:00   
763079  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  20:00:00   
763080  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  20:00:00   

              DESC  ENTRIES    EXITS            DATETIME  
763074     REGULAR  8651134  1430855 2017-05-26 00:00:00  
763075     REGULAR  8651156  1430857 2017-05-26 04:00:00  
763076     REGULAR  8651459  1430934 2017-05-26 08:00:00  
763077     REGULAR  8652461  1431057 2017-05-26 12:00:00  
763078     REGULAR  8652911  1431171 2017-05-26 16:00:00  
763079     REGULAR  8653329  1431335 2017-05-26 20:00:00  
763080  RECOVR AUD  8653331  1431335 2017-05-26 20:00:00

From masked df above, we remove the 'regular' observation, having index 763079, because the audited observation is consistent with the prior observation at 16:00:00 and we assume audits are more robust than the typical method of observation collection.  

In [17]:
#remove observation
df.drop(df.index[763079], inplace = True)

In [18]:
#verify removal of observation
mask = ((df["C/A"] == "R504") & 
(df["UNIT"] == "R276") & 
(df["SCP"] == "00-00-01") & 
(df["STATION"] == "VERNON-JACKSON") &
(df["DATE"] == "05/26/2017"))
df[mask]

C/A  UNIT       SCP         STATION        DATE      TIME  \
763074  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  00:00:00   
763075  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  04:00:00   
763076  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  08:00:00   
763077  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  12:00:00   
763078  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  16:00:00   
763080  R504  R276  00-00-01  VERNON-JACKSON  05/26/2017  20:00:00   

              DESC  ENTRIES    EXITS            DATETIME  
763074     REGULAR  8651134  1430855 2017-05-26 00:00:00  
763075     REGULAR  8651156  1430857 2017-05-26 04:00:00  
763076     REGULAR  8651459  1430934 2017-05-26 08:00:00  
763077     REGULAR  8652461  1431057 2017-05-26 12:00:00  
763078     REGULAR  8652911  1431171 2017-05-26 16:00:00  
763080  RECOVR AUD  8653331  1431335 2017-05-26 20:00:00

In [19]:
#check second entry of duplicate entries in df above
# On 2017-05-09 05:00:00
mask = ((df["C/A"] == "G001") & 
(df["UNIT"] == "R151") & 
(df["SCP"] == "00-00-00") & 
(df["STATION"] == "CONEY IS-STILLW") &
(df["DATE"] == "05/09/2017"))
df[mask]

C/A  UNIT       SCP          STATION        DATE      TIME  \
224250  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  01:00:00   
224251  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  05:00:00   
224252  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  05:00:00   
224253  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  09:00:00   
224254  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  13:00:00   
224255  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  17:00:00   
224256  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  21:00:00   

              DESC  ENTRIES   EXITS            DATETIME  
224250     REGULAR   199982  337867 2017-05-09 01:00:00  
224251     REGULAR   200022  337947 2017-05-09 05:00:00  
224252  RECOVR AUD   200021  337947 2017-05-09 05:00:00  
224253     REGULAR   200363  338280 2017-05-09 09:00:00  
224254     REGULAR   200546  338821 2017-05-09 13:00:00  
224255     REGULAR   200860  339305 2017-05-09 17:00:00  
224256     REGULAR   201098  339691 2017-05-09 21:00:00

From masked df above, we remove the 'regular' observation, having index 224251, because the audited observation is consistent with the prior observation at 01:00:00 and the post observation at 09:00:00 we assume audits are more robust than the typical method of observation collection.

In [20]:
#remove observation
df.drop(df.index[224251], inplace = True)

In [21]:
#verify removal of the observation
mask = ((df["C/A"] == "G001") & 
(df["UNIT"] == "R151") & 
(df["SCP"] == "00-00-00") & 
(df["STATION"] == "CONEY IS-STILLW") &
(df["DATE"] == "05/09/2017"))
df[mask]

C/A  UNIT       SCP          STATION        DATE      TIME  \
224250  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  01:00:00   
224252  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  05:00:00   
224253  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  09:00:00   
224254  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  13:00:00   
224255  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  17:00:00   
224256  G001  R151  00-00-00  CONEY IS-STILLW  05/09/2017  21:00:00   

              DESC  ENTRIES   EXITS            DATETIME  
224250     REGULAR   199982  337867 2017-05-09 01:00:00  
224252  RECOVR AUD   200021  337947 2017-05-09 05:00:00  
224253     REGULAR   200363  338280 2017-05-09 09:00:00  
224254     REGULAR   200546  338821 2017-05-09 13:00:00  
224255     REGULAR   200860  339305 2017-05-09 17:00:00  
224256     REGULAR   201098  339691 2017-05-09 21:00:00

In [22]:
#check if there are any duplicates in the observations for exits
(df
 .groupby(["C/A", "UNIT", "SCP", "STATION", "DATE", "DATETIME"])
 .EXITS.count()
 .reset_index()
 .sort_values("EXITS", ascending=False))

C/A  UNIT       SCP          STATION        DATE  \
0        A002  R051  02-00-00            59 ST  04/29/2017   
654035   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654023   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654024   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654025   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654026   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654027   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654028   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654029   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654030   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654031   R145  R032  00-00-03   TIMES SQ-42 ST  05/12/2017   
654032   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654033   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654034   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654036   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654021   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654037   R145  R032  00-00-03   TIMES SQ-42 ST  05/13/2017   
654038   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654039   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654040   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654041   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654042   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654043   R145  R032  00-00-03   TIMES SQ-42 ST  05/14/2017   
654044   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654045   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654046   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654047   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654048   R145  R032  00-00-03   TIMES SQ-42 ST  05/15/2017   
654022   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
654020   R145  R032  00-00-03   TIMES SQ-42 ST  05/11/2017   
...       ...   ...       ...              ...         ...   
327026   N181  R357  00-00-01  AQUEDUCT N.COND  05/03/2017   
327025   N181  R357  00-00-01  AQUEDUCT N.COND  05/03/2017   
327024   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327023   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
326998   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
326999   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
327000   N181  R357  00-00-00  AQUEDUCT N.COND  06/01/2017   
327001   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327002   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327003   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327004   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327005   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327006   N181  R357  00-00-01  AQUEDUCT N.COND  04/29/2017   
327007   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327008   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327009   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327010   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327011   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327012   N181  R357  00-00-01  AQUEDUCT N.COND  04/30/2017   
327013   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327014   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327015   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327016   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327017   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327018   N181  R357  00-00-01  AQUEDUCT N.COND  05/01/2017   
327019   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327020   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327021   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
327022   N181  R357  00-00-01  AQUEDUCT N.COND  05/02/2017   
981044  TRAM2  R469  00-05-01    RIT-ROOSEVELT  06/02/2017   

                  DATETIME  EXITS  
0      2017-04-29 00:00:00      1  
654035 2017-05-13 12:00:00      1  
654023 2017-05-11 12:00:00      1  
654024 2017-05-11 16:

Data is consistent. There are no duplicate observations for exits.

In [23]:
#Now that uniqueness of entries and exits have been verified, reset the indices
# drop duplicate indices

df=df.reset_index()
print(df.shape)
df.tail()

(981045, 11)


index    C/A  UNIT       SCP        STATION        DATE      TIME  \
981040  981042  TRAM2  R469  00-05-01  RIT-ROOSEVELT  06/02/2017  05:00:00   
981041  981043  TRAM2  R469  00-05-01  RIT-ROOSEVELT  06/02/2017  09:00:00   
981042  981044  TRAM2  R469  00-05-01  RIT-ROOSEVELT  06/02/2017  13:00:00   
981043  981045  TRAM2  R469  00-05-01  RIT-ROOSEVELT  06/02/2017  17:00:00   
981044  981046  TRAM2  R469  00-05-01  RIT-ROOSEVELT  06/02/2017  21:00:00   

           DESC  ENTRIES  EXITS            DATETIME  
981040  REGULAR     5554    299 2017-06-02 05:00:00  
981041  REGULAR     5554    299 2017-06-02 09:00:00  
981042  REGULAR     5554    299 2017-06-02 13:00:00  
981043  REGULAR     5554    299 2017-06-02 17:00:00  
981044  REGULAR     5554    299 2017-06-02 21:00:00

Df above shows reindexing is successful.

In [24]:
# review entries for consistency in values

dfdaily = df.groupby\
                (["C/A", "UNIT", "SCP", "STATION", "DATE"])\
                .ENTRIES.first().reset_index()
        
df.head()

index   C/A  UNIT       SCP STATION        DATE      TIME     DESC  \
0      0  A002  R051  02-00-00   59 ST  04/29/2017  00:00:00  REGULAR   
1      1  A002  R051  02-00-00   59 ST  04/29/2017  04:00:00  REGULAR   
2      2  A002  R051  02-00-00   59 ST  04/29/2017  08:00:00  REGULAR   
3      3  A002  R051  02-00-00   59 ST  04/29/2017  12:00:00  REGULAR   
4      4  A002  R051  02-00-00   59 ST  04/29/2017  16:00:00  REGULAR   

   ENTRIES    EXITS            DATETIME  
0  6157740  2085315 2017-04-29 00:00:00  
1  6157777  2085319 2017-04-29 04:00:00  
2  6157810  2085353 2017-04-29 08:00:00  
3  6157963  2085453 2017-04-29 12:00:00  
4  6158212  2085529 2017-04-29 16:00:00

In [25]:
#add prior entries and its date as columns to the df for easier interpretation of consistency in values 
# define two new columns using 
dfdaily[["PREVDATE", "PREVENTRIES"]] = (dfdaily
                                                       .groupby(["C/A", "UNIT", "SCP", "STATION"])["DATE", "ENTRIES"]
                                                       .transform(lambda grp: grp.shift(1)))

In [26]:
#preview df to verify new columns
dfdaily.head(50)

C/A  UNIT       SCP STATION        DATE  ENTRIES    PREVDATE  PREVENTRIES
0   A002  R051  02-00-00   59 ST  04/29/2017  6157740         NaN          NaN
1   A002  R051  02-00-00   59 ST  04/30/2017  6158637  04/29/2017    6157740.0
2   A002  R051  02-00-00   59 ST  05/01/2017  6159107  04/30/2017    6158637.0
3   A002  R051  02-00-00   59 ST  05/02/2017  6160508  05/01/2017    6159107.0
4   A002  R051  02-00-00   59 ST  05/03/2017  6162061  05/02/2017    6160508.0
5   A002  R051  02-00-00   59 ST  05/04/2017  6163517  05/03/2017    6162061.0
6   A002  R051  02-00-00   59 ST  05/05/2017  6165120  05/04/2017    6163517.0
7   A002  R051  02-00-00   59 ST  05/06/2017  6166390  05/05/2017    6165120.0
8   A002  R051  02-00-00   59 ST  05/07/2017  6167259  05/06/2017    6166390.0
9   A002  R051  02-00-00   59 ST  05/08/2017  6167955  05/07/2017    6167259.0
10  A002  R051  02-00-00   59 ST  05/09/2017  6169536  05/08/2017    6167955.0
11  A002  R051  02-00-00   59 ST  05/10/2017  6171059  05/09/2017    6169536.0
12  A002  R051  02-00-00   59 ST  05/11/2017  6172600  05/10/2017    6171059.0
13  A002  R051  02-00-00   59 ST  05/12/2017  6174189  05/11/2017    6172600.0
14  A002  R051  02-00-00   59 ST  05/13/2017  6175956  05/12/2017    6174189.0
15  A002  R051  02-00-00   59 ST  05/14/2017  6176825  05/13/2017    6175956.0
16  A002  R051  02-00-00   59 ST  05/15/2017  6177671  05/14/2017    6176825.0
17  A002  R051  02-00-00   59 ST  05/16/2017  6179262  05/15/2017    6177671.0
18  A002  R051  02-00-00   59 ST  05/17/2017  6180269  05/16/2017    6179262.0
19  A002  R051  02-00-00   59 ST  05/18/2017  6181793  05/17/2017    6180269.0
20  A002  R051  02-00-00   59 ST  05/19/2017  6183294  05/18/2017    6181793.0
21  A002  R051  02-00-00   59 ST  05/20/2017  6184841  05/19/2017    6183294.0
22  A002  R051  02-00-00   59 ST  05/21/2017  6185634  05/20/2017    6184841.0
23  A002  R051  02-00-00   59 ST  05/22/2017  6186215  05/21/2017    6185634.0
24  A002  R051  02-00-00   59 ST  05/23/2017  6187676  05/22/2017    6186215.0
25  A002  R051  02-00-00   59 ST  05/24/2017  6189483  05/23/2017    6187676.0
26  A002  R051  02-00-00   59 ST  05/25/2017  6191488  05/24/2017    6189483.0
27  A002  R051  02-00-00   59 ST  05/26/2017  6193582  05/25/2017    6191488.0
28  A002  R051  02-00-00   59 ST  05/27/2017  6195217  05/26/2017    6193582.0
29  A002  R051  02-00-00   59 ST  05/28/2017  6195898  05/27/2017    6195217.0
30  A002  R051  02-00-00   59 ST  05/29/2017  6196569  05/28/2017    6195898.0
31  A002  R051  02-00-00   59 ST  05/30/2017  6197230  05/29/2017    6196569.0
32  A002  R051  02-00-00   59 ST  05/31/2017  6198819  05/30/2017    6197230.0
33  A002  R051  02-00-00   59 ST  06/01/2017  6200419  05/31/2017    6198819.0
34  A002  R051  02-00-00   59 ST  06/02/2017  6202055  06/01/2017    6200419.0
35  A002  R051  02-00-01   59 ST  04/29/2017  5580416         NaN          NaN
36  A002  R051  02-00-01   59 ST  04/30/2017  5581232  04/29/2017    5580416.0
37  A002  R051  02-00-01   59 ST  05/01/2017  5581851  04/30/2017    5581232.0
38  A002  R051  02-00-01   59 ST  05/02/2017  5583047  05/01/2017    5581851.0
39  A002  R051  02-00-01   59 ST  05/03/2017  5584235  05/02/2017    5583047.0
40  A002  R051  02-00-01   59 ST  05/04/2017  5585515  05/03/2017    5584235.0
41  A002  R051  02-00-01   59 ST  05/05/2017  5586785  05/04/2017    5585515.0
42  A002  R051  02-00-01   59 ST  05/06/2017  5587839  05/05/2017    5586785.0
43  A002  R051  02-00-01   59 ST  05/07/2017  5588457  05/06/2017    5587839.0
44  A002  R051  02-00-01   59 ST  05/08/2017  5588927  05/07/2017    5588457.0
45  A002  R051  02-00-01   59 ST  05/09/2017  5590002  05/08/2017    5588927.0
46  A002  R051  02-00-01   59 ST  05/10/2017  5591142  05/09/2017    5590002.0
47  A002  R051  02-00-01   59 ST  05/11/2017  5592255  05/10/2017    5591142.0
48  A002  R051  02-00-01   59 ST  05/12/2017  5593449  05/11/2017    5592255.0
49  A002  R051  02-00-01   59 ST  05/13/2017  5594253  

In [27]:
# Drop observations with NAN values for previous date
dfdaily.dropna(subset=["PREVDATE"], axis=0, inplace=True)

In [28]:
#verify observations of NANs for PREVDATE are dropped
dfdaily.head()

C/A  UNIT       SCP STATION        DATE  ENTRIES    PREVDATE  PREVENTRIES
1  A002  R051  02-00-00   59 ST  04/30/2017  6158637  04/29/2017    6157740.0
2  A002  R051  02-00-00   59 ST  05/01/2017  6159107  04/30/2017    6158637.0
3  A002  R051  02-00-00   59 ST  05/02/2017  6160508  05/01/2017    6159107.0
4  A002  R051  02-00-00   59 ST  05/03/2017  6162061  05/02/2017    6160508.0
5  A002  R051  02-00-00   59 ST  05/04/2017  6163517  05/03/2017    6162061.0

In [29]:
#check if any previous entries are larger than current ones
dfdaily[dfdaily["ENTRIES"] < dfdaily["PREVENTRIES"]]

C/A  UNIT       SCP          STATION        DATE     ENTRIES  \
1102     A010  R080  00-00-05       57 ST-7 AV  05/16/2017        3922   
1191     A011  R080  01-00-00       57 ST-7 AV  04/30/2017   887017249   
1192     A011  R080  01-00-00       57 ST-7 AV  05/01/2017   887015428   
1193     A011  R080  01-00-00       57 ST-7 AV  05/02/2017   887012755   
1194     A011  R080  01-00-00       57 ST-7 AV  05/03/2017   887009153   
1195     A011  R080  01-00-00       57 ST-7 AV  05/04/2017   887005522   
1196     A011  R080  01-00-00       57 ST-7 AV  05/05/2017   887001929   
1197     A011  R080  01-00-00       57 ST-7 AV  05/06/2017   886998688   
1198     A011  R080  01-00-00       57 ST-7 AV  05/07/2017   886996727   
1199     A011  R080  01-00-00       57 ST-7 AV  05/08/2017   886995127   
1200     A011  R080  01-00-00       57 ST-7 AV  05/09/2017   886991859   
1201     A011  R080  01-00-00       57 ST-7 AV  05/10/2017   886988488   
1202     A011  R080  01-00-00       57 ST-7 AV  05/11/2017   886985174   
1203     A011  R080  01-00-00       57 ST-7 AV  05/12/2017   886981449   
1204     A011  R080  01-00-00       57 ST-7 AV  05/13/2017   886977871   
1205     A011  R080  01-00-00       57 ST-7 AV  05/14/2017   886975801   
1206     A011  R080  01-00-00       57 ST-7 AV  05/15/2017   886974199   
1207     A011  R080  01-00-00       57 ST-7 AV  05/16/2017   886970967   
1208     A011  R080  01-00-00       57 ST-7 AV  05/17/2017   886967490   
1209     A011  R080  01-00-00       57 ST-7 AV  05/18/2017   886964117   
1210     A011  R080  01-00-00       57 ST-7 AV  05/19/2017   886960596   
1211     A011  R080  01-00-00       57 ST-7 AV  05/20/2017   886957437   
1212     A011  R080  01-00-00       57 ST-7 AV  05/21/2017   886955738   
1213     A011  R080  01-00-00       57 ST-7 AV  05/22/2017   886953767   
1214     A011  R080  01-00-00       57 ST-7 AV  05/23/2017   886950335   
1215     A011  R080  01-00-00       57 ST-7 AV  05/24/2017   886946671   
1216     A011  R080  01-00-00       57 ST-7 AV  05/25/2017   886943007   
1217     A011  R080  01-00-00       57 ST-7 AV  05/26/2017   886939431   
1218     A011  R080  01-00-00       57 ST-7 AV  05/27/2017   886936242   
1219     A011  R080  01-00-00       57 ST-7 AV  05/28/2017   886934373   
...       ...   ...       ...              ...         ...         ...   
161264   R646  R110  01-00-01  FLATBUSH AV-B.C  05/26/2017  1507935000   
161265   R646  R110  01-00-01  FLATBUSH AV-B.C  05/27/2017  1507933341   
161266   R646  R110  01-00-01  FLATBUSH AV-B.C  05/28/2017  1507932833   
161267   R646  R110  01-00-01  FLATBUSH AV-B.C  05/29/2017  1507932426   
161268   R646  R110  01-00-01  FLATBUSH AV-B.C  05/30/2017  1507932025   
161269   R646  R110  01-00-01  FLATBUSH AV-B.C  05/31/2017  1507930476   
161270   R646  R110  01-00-01  FLATBUSH AV-B.C  06/01/2017  1507928938   
161271   R646  R110  01-00-01  FLATBUSH AV-B.C  06/02/2017  1507927447   
162119   R730  R431  00-00-04  EASTCHSTER/DYRE  05/06/2017  1560221266   
162120   R730  R431  00-00-04  EASTCHSTER/DYRE  05/07/2017  1560221264   
162122   R730  R431  00-00-04  EASTCHSTER/DYRE  05/09/2017  1560220746   
162123   R730  R431  00-00-04  EASTCHSTER/DYRE  05/10/2017  1560220212   
162124   R730  R431  00-00-04  EASTCHSTER/DYRE  05/11/2017  1560219688   
162125   R730  R431  00-00-04  EASTCHSTER/DYRE  05/12/2017  1560219196   
162126   R730  R431  00-00-04  EASTCHSTER/DYRE  05/13/2017  1560218724   
162129   R730  R431  00-00-04  EASTCHSTER/DYRE  05/16/2017  1560218145   
162130   R730  R431  00-00-04  EASTCHSTER/DYRE  05/17/2017  1560217623   
162131   R730  R431  00-00-04  EASTCHSTER/DYRE  05/18/2017  1560217082   
162132   R730  R431  00-00-04  EASTCHSTER/DYRE  05/19/2017  1560216574   
162133   R730  R431  00-00-04  EASTCHSTER/DYRE  05/20/2017  1560216050   
162136   R730  R431  00-00-04  EASTCHSTER/DYRE  05/23/2017  1560215566   
162137   R730  R431  00-00-04  EASTCHSTER/DYRE  05/24/2017  1560215026   
162138   R730 

From the df above, there are 1337 observations in which the previous observation for entry is larger than the current entry. We decided to remove these observations.

In [32]:
#remove all observations where the previous observation for entry is larger than the current entry
dfdaily = dfdaily[dfdaily["ENTRIES"] >= dfdaily["PREVENTRIES"]]


In [35]:
dfdaily.shape

(157598, 8)